version: '3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ENCRYPTION=${JWT_ENCRYPTION}