version: '3'
services:

  server:
    restart: always
    depends_on:
      - database
      - redis
    build:
      context: ./
    volumes:
      - ./src/:/app/src
    links: 
      - database
      - redis
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_ENCRYPTION=${JWT_ENCRYPTION}

  database:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DATABASE}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  nginx: 
    container_name: nginx    
    build :
      context: ./../nginx
    hostname: nginx
    ports:
      - "443:443"
    depends_on:
      - server
      